export const products = [
    {
        id: "rec43w3ipXvP28vog",
        title: "high-back bench",
        company: "ikea",
        image: "./assets/img/product-1.jpeg",
        price: 9.99,
    },
    {
        id: "rec4f2RIftFCb7aHh",
        title: "albany table",
        company: "marcos",
        image: "./assets/img/product-2.jpeg",
        price: 79.99,
    },
    {
        id: "rec8kkCmSiMkbkiko",
        title: "accent chair",
        company: "caressa",
        image: "./assets/img/product-3.jpeg",
        price: 25.99,
    },
    {
        id: "recBohCqQsot4Q4II",
        title: "wooden table",
        company: "caressa",
        image: "./assets/img/product-4.jpeg",
        price: 45.99,
    },
    {
        id: "recDG1JRZnbpRHpoy",
        title: "dining table",
        company: "caressa",
        image: "./assets/img/product-5.jpeg",
        price: 6.99,
    },
    {
        id: "recNWGyP7kjFhSqw3",
        title: "sofa set",
        company: "liddy",
        image: "./assets/img/product-6.jpeg",
        price: 69.99,
    },
    {
        id: "recZEougL5bbY4AEx",
        title: "modern bookshelf",
        company: "marcos",
        image: "./assets/img/product-7.jpeg",
        price: 8.99,
    },
    {
        id: "recjMK1jgTb2ld7sv",
        title: "emperor bed",
        company: "liddy",
        image: "./assets/img/product-8.jpeg",
        price: 21.99,
    },
    {
        id: "recmg2a1ctaEJNZhu",
        title: "utopia sofa",
        company: "marcos",
        image: "./assets/img/product-9.jpeg",
        price: 39.95,
    },
    {
        id: "recvKMNR3YFw0bEt3",
        title: "entertainment center",
        company: "liddy",
        image: "./assets/img/product-10.jpeg",
        price: 29.98,
    },
    {
        id: "recxaXFy5IW539sgM",
        title: "albany sectional",
        company: "ikea",
        image: "./assets/img/product-11.jpeg",
        price: 10.99,
    },
    {
        id: "recyqtRglGNGtO4Q5",
        title: "leather sofa",
        company: "liddy",
        image: "./assets/img/product-12.jpeg",
        price: 9.99,
    },
];
