const data = [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla finibus, nibh sed ornare consequat, risus lorem vestibulum augue, et bibendum mi nisi at sem. Duis consectetur, nisi in venenatis semper, libero nunc mattis quam, at cursus elit est vel urna. Vestibulum elementum, ex porttitor aliquet sodales, felis est maximus nibh, at mollis nisl felis at ipsum. Vestibulum enim est, sodales in sodales ut, commodo sodales justo. Duis a ex tincidunt, viverra libero nec, congue tortor. Morbi accumsan justo sed orci consequat, egestas convallis ipsum euismod. Etiam vel congue nisl. Aliquam ornare lorem in gravida feugiat. Proin tincidunt metus sit amet vestibulum rhoncus. Sed molestie blandit risus, volutpat aliquam lorem venenatis sit amet. Suspendisse potenti. Etiam tincidunt, magna porttitor venenatis pretium, lectus ligula pretium nisi, vel ornare diam nunc nec metus.",
    "Sed a egestas nulla. Nam ac neque vel felis facilisis elementum. Sed a dolor ut tellus sagittis pretium. Morbi leo magna, pellentesque ac ante a, lobortis facilisis lectus. Quisque sollicitudin magna vel venenatis interdum. Vivamus viverra eros vel tellus elementum facilisis. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin porta ultricies urna. Mauris vel ex condimentum, eleifend mi et, molestie mauris. Proin eu est venenatis, gravida nunc non, fermentum elit. Aenean ullamcorper volutpat sem vel sodales. Aliquam quis sagittis ante, non tristique ipsum. Donec id arcu varius, fringilla orci nec, finibus urna. Curabitur viverra varius enim eget vestibulum. Curabitur nunc ante, facilisis ut justo non, dapibus luctus sem.",
    "Praesent in tortor vitae ligula vulputate rutrum sed eu risus. Donec ullamcorper massa tortor, nec suscipit mauris dictum eu. Sed eu orci varius, scelerisque purus ut, accumsan augue. Curabitur euismod eget sapien eget mattis. Ut et tortor dictum, aliquet purus sit amet, porta arcu. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Quisque maximus tortor a ultrices ultrices. Fusce aliquam commodo libero id tincidunt. Cras nunc dui, tincidunt ac egestas vitae, commodo non dolor. Nullam varius tempus neque quis tincidunt. Donec mattis nisl facilisis, laoreet enim et, venenatis orci. Etiam efficitur iaculis efficitur. Morbi id sem vel enim fringilla commodo. Donec gravida consectetur nisi id semper. Praesent eget nibh eget massa cursus consectetur eget nec sem. Duis finibus ligula in velit fermentum laoreet.",
    "Curabitur nec nibh id est tempor pellentesque eget vel purus. Donec eget neque vel diam pretium tempus ac at eros. Aenean a nunc venenatis, facilisis ante egestas, egestas ante. Proin auctor dignissim eros et ultricies. Sed elementum ultrices libero sit amet sollicitudin. Curabitur fringilla sed tortor nec malesuada. Duis quis tempus nunc. Ut at justo eget augue malesuada lobortis id vitae diam. Fusce a dignissim est. Maecenas nec auctor elit. Maecenas vestibulum quis quam non varius. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed id suscipit ipsum. Integer pretium volutpat iaculis.",
    "Suspendisse porta nunc ac consectetur laoreet. Aenean efficitur mi in tincidunt cursus. Sed augue neque, malesuada faucibus mollis non, dignissim non tellus. Donec ut euismod augue. Nunc blandit diam a mauris viverra aliquam. Pellentesque suscipit libero id enim sollicitudin lobortis. Suspendisse non consectetur velit. Nunc id tincidunt ipsum. Pellentesque pharetra interdum lorem, a rutrum justo. Curabitur in semper erat. Nullam lobortis volutpat lacus. Quisque et suscipit arcu. Praesent neque elit, luctus ut neque a, viverra scelerisque leo. Nulla eget felis ac massa dapibus sodales. Aenean tempus ut quam in semper. Fusce eget justo tellus.",
    "In hac habitasse platea dictumst. Integer in est ac ex pharetra viverra. In imperdiet libero lacinia risus semper dictum. Morbi quam felis, tempor nec mattis eu, dictum ac libero. Morbi leo leo, interdum in mattis ut, sollicitudin id arcu. Phasellus nec volutpat metus, sed facilisis justo. Duis commodo lacus dolor, eu tempus dui vehicula vitae. Interdum et malesuada fames ac ante ipsum primis in faucibus. Sed elementum efficitur turpis, at feugiat nunc hendrerit sit amet.",
    "Sed et arcu pretium mi fringilla finibus pellentesque sed libero. Donec id mauris volutpat, commodo libero eu, placerat velit. Duis blandit, dolor sed rutrum rutrum, neque orci pellentesque orci, id venenatis velit erat vitae magna. Fusce fringilla pretium elit, ut mattis est elementum vel. Suspendisse malesuada vitae felis eget tempor. Mauris rutrum aliquam felis at vestibulum. Quisque convallis nisi a mauris tristique ullamcorper sed dictum justo. Suspendisse potenti. Donec at posuere diam, quis elementum nulla.",
    "Sed mollis elementum mi a suscipit. Etiam ac neque ante. Vivamus sed massa eros. Quisque lobortis maximus ante. Proin pretium justo ac nunc porta, iaculis euismod ante faucibus. Nunc tempus efficitur enim vitae lobortis. Nunc dignissim ligula non egestas congue.",
    "Pellentesque a lectus lacus. Integer in ornare purus, in elementum quam. Phasellus sed ex non purus tempus auctor. Fusce maximus sem in massa mollis rutrum. Fusce porta, mauris pharetra efficitur pharetra, dui tellus gravida nunc, eu sagittis leo mi vel ante. Fusce eleifend, nisl eget molestie commodo, diam elit tempor massa, eu laoreet odio justo a leo. Proin sed ipsum et eros placerat imperdiet vel id lorem. Nulla facilisi. Donec porttitor in massa ut luctus. Nunc gravida a ligula in lacinia. Nullam dapibus quis ipsum eu rhoncus. Praesent nec urna pretium, fermentum dolor a, pretium ligula. Phasellus pharetra, nibh et placerat dapibus, lectus augue eleifend magna, vel pellentesque eros nisl in neque. Duis interdum ultricies turpis vitae luctus. Fusce tortor libero, fringilla nec mattis sit amet, molestie nec neque.",
    "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Integer scelerisque lacus sit amet varius pharetra. Fusce ut quam ut nisi pretium suscipit nec sit amet sapien. Praesent posuere augue eget orci iaculis blandit. Sed quis sem in purus ultrices tempus. Phasellus hendrerit diam tincidunt, sollicitudin nisl eu, consectetur dolor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec ut placerat orci, sit amet ullamcorper libero. Maecenas et ultricies sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Proin viverra quam lectus, nec placerat tellus viverra sed. In ullamcorper semper ex, bibendum feugiat odio blandit semper.",
];

const form = document.querySelector(".c-generator-form");
const input = document.querySelector(".c-generator-form__input");
const container = document.querySelector(".l-paragraphs");

const randomHelper = () => {
    return Math.floor(Math.random() * data.length);
};

const generateHandler = (event) => {
    event.preventDefault();
    container.innerHTML = "";
    const count = input.value;
    for (let counter = 1; counter <= count; counter++) {
        let index = randomHelper();

        const paragraph = document.createElement("p");
        paragraph.classList.add("c-paragraph");
        paragraph.textContent = data[index];
        container.append(paragraph);
    }
};

form.addEventListener("submit", generateHandler);
